import type { Metadata } from "next";
import { Sen } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const sen = Sen({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="w-full max-w-md m-auto h-full">
      <body className={`${sen.className} w-full relative h-full`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
